#ifndef PCMFLOWDEVICE_VERSION_H
#define PCMFLOWDEVICE_VERSION_H

#define PCMFLOWDEVICE_VERSION_MAJOR 0
#define PCMFLOWDEVICE_VERSION_MINOR 1
#define PCMFLOWDEVICE_VERSION_PATCH 0
#define PCMFLOWDEVICE_VERSION_STR "0.1.0"

#endif // PCMFLOWDEVICE_VERSION_H
